nodeLinker: node-modules

githubDeviceOAuthAppClientId: 'Ov23liErAVwF44N73iQ9'
githubDeviceAuthScope: 'volvo-cars'


npmScopes:
  volvo-cars:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.pkg.github.com/volvo-cars"

plugins:
  - path: ./bundles/@yarnpkg/plugin-github-device-auth.js