nodeLinker: node-modules

githubDeviceAuth:
  clientId: 'Ov23liErAVwF44N73iQ9'
  scope: 'volvo-cars'

npmScopes:
  volvo-cars:
    npmAlwaysAuth: true
    npmRegistryServer: 'https://npm.pkg.github.com/volvo-cars'

plugins:
  - path: ./bundles/@yarnpkg/plugin-github-device-auth.js
