name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Enable Corepack
        run: |
          npm install -g corepack@latest
          corepack enable

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Type Check
        run: yarn check-types

      - name: Format Check
        run: yarn format:check

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build
